#!/usr/bin/env bash

get record info() {
	local domain=$1
	local subdomain=$2

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}"; do
		record=$(dig +short "$sub.$domain")
		record_type=$(dig +short "$sub.$domain" | awk '{ print toupper($1) }')
		destination=$(dig +short "$sub.$domain" | awk '{ print $1 }')

		if [ -n "$record" ]; then
			echo "The subdomain $sub is a $record_type record and points to $destination"
		fi
	done
}

get_record_info "$1" "$2"
