#!/usr/bin/env bash
# Configuring a Ubuntu machine with nginx

sudo apt update
sudo apt install nginx
sudo systemctl start nginx

sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

sudo systemctl restart nginx
