#!/usr/bin/env bash
# A bash script that manages manage_my_process.

if [ "$1" == "start" ]
then
	./manage_my_process &
	sudo echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	kill "$(pgrep -f /manage_my_process)"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "started" ]
then
	kill "$(pgrep -f /manage_my_process)"
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	sudo echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
else
	echo "Usage: manage_my_process {start|stop|started}"
fi
