#!/usr/bin/env bash
# Bash script that:
#+ Indefinitely writes I am alive! to the file /tmp/my_process
#+ In between every I am alive! message, the program should pause for 2 seconds


if [ "$1" == "start" ]
then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "started" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
else
	echo "Usage: manage_my_process {start|stop|started}"
fi
