#!/usr/bin/env bash
# A Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
#+ Requirements:
#+ You cannot use ps.

for pid in /proc/[0-9]*
do
    if [ -f "${pid}/comm" ] && grep -q bash "${pid}/comm"
    then
        echo "${pid##*/}: $(cat "${pid}/comm")"
    fi
done
