#!/usr/bin/env bash
# A Bash script that displays:
#+ To infinity and beyond indefinitely
#+ With a sleep 2 in between each iteration
#+ I am invincible!!! when receiving a SIGTERM signal

num=1
while [ $num ]
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' 15
done
