#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
#+ Displaying:
#+ username
#+ user id
#+ Home directory path for the user

while IFS=: read -r line
do
    echo "$line" | cut -d ":" -f 1, 3, 6
done < /etc/passwd
