#!/usr/bin/env bash
# Conditions nested.

i=1
while [ $i -le 9 ]
do
    if test $i == 3
    then
        echo "bad luck"
    elif test $i == 7
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$(( i + 1))
done
